#!/usr/bin/env bash
#
# generate-cursor.sh — Regenerate .cursor/ from plugin sources (packs/, skills/, commands/, reference/).
#
# Cursor support is FROZEN at the v5.1 feature set (CHANGELOG v5.2.1 platform
# strategy). This generator does NOT unfreeze Cursor or forward-port v5.2+
# capabilities. Its job is to make parity HONEST and CONSISTENT: every committed
# .cursor/ file carries the same frozen-version note so a Cursor user knows the
# platform is intentionally behind, not stale-by-accident.
#
# Usage:
#   ./scripts/generate-cursor.sh                 # regenerate ./cursor in place
#   ./scripts/generate-cursor.sh --target DIR    # operate on a different repo root
#
# Pure function: (plugin.json, packs/, skills/, commands/, reference/) -> .cursor/**. Deterministic and
# idempotent — running twice produces byte-identical output. Offline-safe: zero
# network calls.
#
# Transform rules table (see docs/plans + design.md for this batch):
#   packs/{name}/rules.md            -> .cursor/rules/temper-pack-{name}.mdc
#   skills/{name}/SKILL.md           -> .cursor/rules/temper-skill-{name}.mdc
#   capability flag enabled in temper.config -> .cursor/rules/temper-capability-{name}.mdc
#   reference/{name}.md       -> .cursor/rules/temper-ref-{name}.mdc
#   commands/{name}.md               -> .cursor/commands/temper[-{name}].md
#   plugin.json version                      -> .cursor/VERSION (bare X.Y.Z)

set -euo pipefail

# --- Resolve repo root -------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Optional --target override (used by install-cursor.sh local-repo branch).
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target) REPO_ROOT="$(cd "$2" && pwd)"; shift 2 ;;
        *) echo "Usage: $0 [--target DIR]" >&2; exit 2 ;;
    esac
done

PJ="$REPO_ROOT/.claude-plugin/plugin.json"
REF_DIR="$REPO_ROOT/reference"
CURSOR_DIR="$REPO_ROOT/.cursor"
RULES_DIR="$CURSOR_DIR/rules"
COMMANDS_DIR="$CURSOR_DIR/commands"
CONFIG="$REPO_ROOT/.claude/temper.config"

if [[ ! -f "$PJ" ]]; then
    echo "FAIL: plugin.json not found at $PJ" >&2
    exit 1
fi
for d in skills commands packs; do
    if [[ ! -d "$REPO_ROOT/$d" ]]; then
        echo "FAIL: $d/ not found at $REPO_ROOT/$d" >&2
        exit 1
    fi
done

command -v python3 >/dev/null 2>&1 || { echo "FAIL: python3 is required" >&2; exit 1; }

VERSION=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['version'])" "$PJ")

# --- Stale-file cleanup ------------------------------------------------------
# Wholesale regenerate: remove the derived directory first so deleted sources
# do not leave orphans behind. mcp.json is NOT derived (hand-authored) — it is
# preserved across regeneration.
PRESERVE_MCP=""
if [[ -f "$CURSOR_DIR/mcp.json" ]]; then
    PRESERVE_MCP=$(cat "$CURSOR_DIR/mcp.json")
fi
rm -rf "$CURSOR_DIR"
mkdir -p "$RULES_DIR" "$COMMANDS_DIR"
if [[ -n "$PRESERVE_MCP" ]]; then
    printf '%s\n' "$PRESERVE_MCP" > "$CURSOR_DIR/mcp.json"
fi

# --- Frozen-note header (constant) -------------------------------------------
frozen_note() {
    # $1 = repo-relative source path of the generated file
    local src="$1"
    cat <<EOF
<!--
  AUTO-GENERATED by scripts/generate-cursor.sh from plugin sources.
  Cursor support FROZEN at v5.1 feature set (CHANGELOG v5.2.1).
  This file is regenerated on every release for consistency; do not hand-edit.
  Source: $src
-->

EOF
}

emit_rule() {
    # $1 = target path under .cursor/rules/
    # $2 = description string (already shell-quoted-safe; we wrap in double quotes)
    # $3 = alwaysApply value (true|false)
    # $4 = repo-relative source path for the frozen-note
    # stdin = body content (markdown without frontmatter)
    local target="$1" desc="$2" always="$3" src="$4"
    {
        printf -- '---\n'
        printf 'description: "%s"\n' "$desc"
        printf 'alwaysApply: %s\n' "$always"
        printf -- '---\n\n'
        frozen_note "$src"
        cat
    } > "$target"
}

# Extract a YAML frontmatter `description:` value from a source file, falling
# back to the first non-empty markdown heading. Returns empty string if neither
# is found.
derive_description() {
    python3 - "$1" <<'PY'
import re, sys
path = sys.argv[1]
desc = None
try:
    text = open(path, encoding='utf-8').read()
except OSError:
    sys.exit(0)
# YAML frontmatter block
m = re.match(r'^---\s*\n(.*?)\n---\s*\n', text, re.DOTALL)
if m:
    fm = m.group(1)
    dm = re.search(r'^description:\s*["\']?(.*?)["\']?\s*$', fm, re.MULTILINE)
    if dm:
        desc = dm.group(1).strip().strip('"').strip("'")
if not desc:
    # First non-empty markdown heading
    for line in text.splitlines():
        s = line.strip()
        if s.startswith('#'):
            desc = s.lstrip('#').strip()
            break
if desc:
    # Escape any embedded double quotes for safe YAML emission.
    print(desc.replace('"', '\\"'))
PY
}

# Strip a leading YAML frontmatter block from stdin, return the body.
strip_frontmatter() {
    python3 - <<'PY'
import re, sys
text = sys.stdin.read()
m = re.match(r'^---\s*\n.*?\n---\s*\n?', text, re.DOTALL)
if m:
    sys.stdout.write(text[m.end():])
else:
    sys.stdout.write(text)
PY
}

# --- 1. Packs ----------------------------------------------------------------
shopt -s nullglob
PACK_NAMES=()
for pack_dir in "$REPO_ROOT"/packs/*/; do
    name=$(basename "$pack_dir")
    [[ "$name" == "stacks" ]] && continue
    PACK_NAMES+=("$name")
done
# Deterministic enumeration (sorted) — required for byte-stable output.
IFS=$'\n' read -r -d '' -a PACK_NAMES_SORTED < <(printf '%s\n' "${PACK_NAMES[@]}" | sort && printf '\0') || true
unset IFS

for name in "${PACK_NAMES_SORTED[@]}"; do
    src_rules="$REPO_ROOT/packs/$name/rules.md"
    [[ -f "$src_rules" ]] || continue
    target="$RULES_DIR/temper-pack-$name.mdc"
    desc="Temper quality pack: $name"
    # Strip a leading "# Pack" heading line if the body already has one — we
    # keep pack bodies verbatim otherwise.
    { strip_frontmatter < "$src_rules"; } | emit_rule "$target" "$desc" "false" "packs/$name/rules.md"
done

# --- 2. Skills ---------------------------------------------------------------
SKILL_NAMES=()
for skill_dir in "$REPO_ROOT"/skills/*/; do
    name=$(basename "$skill_dir")
    SKILL_NAMES+=("$name")
done
IFS=$'\n' read -r -d '' -a SKILL_NAMES_SORTED < <(printf '%s\n' "${SKILL_NAMES[@]}" | sort && printf '\0') || true
unset IFS

for name in "${SKILL_NAMES_SORTED[@]}"; do
    src_skill="$REPO_ROOT/skills/$name/SKILL.md"
    [[ -f "$src_skill" ]] || continue
    target="$RULES_DIR/temper-skill-$name.mdc"
    desc=$(derive_description "$src_skill")
    [[ -z "$desc" ]] && desc="Temper skill: $name"
    # temper-core is the only always-on rule (mirrors committed behavior).
    if [[ "$name" == "temper-core" ]]; then
        always="true"
    else
        always="false"
    fi
    { strip_frontmatter < "$src_skill"; } | emit_rule "$target" "$desc" "$always" "skills/$name/SKILL.md"
done

# --- 3. Capabilities ---------------------------------------------------------
# Enumerate enabled capability flags from temper.config. Each enabled flag maps
# to a .mdc. Content is sourced from the matching reference doc where one
# exists (the reference doc IS the source behavior); otherwise a minimal stub.
# Flag-name -> reference-doc-name overrides where they differ.
# Map a capability flag name to its backing reference doc name. POSIX case
# (macOS bash 3.2 has no associative arrays). Where names differ it is noted.
cap_to_ref() {
    case "$1" in
        architecture-depth) echo "architecture-depth" ;;
        grill-me)           echo "grill-me" ;;
        config-suggestions) echo "config-suggestions" ;;
        html-review)        echo "plan-review" ;;   # flag name -> ref doc name
        *)                  echo "$1" ;;
    esac
}

CAP_NAMES=()
if [[ -f "$CONFIG" ]]; then
    # Parse the `capabilities:` block: lines like `  name: true`.
    in_caps=0
    while IFS= read -r line; do
        if [[ "$line" =~ ^capabilities: ]]; then
            in_caps=1; continue
        fi
        if [[ $in_caps -eq 1 ]]; then
            # End of block: a non-indented, non-comment line stops the section.
            if [[ "$line" =~ ^[^[:space:]#] ]]; then
                in_caps=0; continue
            fi
            if [[ "$line" =~ ^[[:space:]]+([a-z][a-z0-9-]+):[[:space:]]+true ]]; then
                CAP_NAMES+=("${BASH_REMATCH[1]}")
            fi
        fi
    done < "$CONFIG"
fi
IFS=$'\n' read -r -d '' -a CAP_NAMES_SORTED < <(printf '%s\n' "${CAP_NAMES[@]:-}" | sort -u && printf '\0') || true
unset IFS

for name in "${CAP_NAMES_SORTED[@]:-}"; do
    [[ -z "$name" ]] && continue
    target="$RULES_DIR/temper-capability-$name.mdc"
    desc="Temper capability: $name"
    ref_name=$(cap_to_ref "$name")
    ref_path="$REF_DIR/$ref_name.md"
    if [[ -f "$ref_path" ]]; then
        { strip_frontmatter < "$ref_path"; } | emit_rule "$target" "$desc" "false" "reference/$ref_name.md"
    else
        # Minimal stub — do not invent content the repo does not have.
        body=$'# Capability: '"$name"$'\n\nEnabled in temper.config. See skills/ and reference/ for source behavior.\n'
        printf '%s' "$body" | emit_rule "$target" "$desc" "false" "temper.config:capabilities.$name"
    fi
done

# --- 4. Reference docs -------------------------------------------------------
REF_NAMES=()
for ref_file in "$REF_DIR"/*.md; do
    name=$(basename "$ref_file" .md)
    REF_NAMES+=("$name")
done
IFS=$'\n' read -r -d '' -a REF_NAMES_SORTED < <(printf '%s\n' "${REF_NAMES[@]}" | sort -u && printf '\0') || true
unset IFS

for name in "${REF_NAMES_SORTED[@]}"; do
    # Skip v5.6+-only reference docs: the Cursor export is FROZEN at the v5.1
    # platform track and must not receive post-v5.1 references. pricing.md is
    # v5.6 economics; tokenomics.md carries v5.6 routing + v5.9 Phase 3 levers.
    # Add future frozen-out refs to this case list.
    case "$name" in
        pricing|tokenomics) continue ;;
    esac
    src_ref="$REF_DIR/$name.md"
    target="$RULES_DIR/temper-ref-$name.mdc"
    desc="Temper reference: $name"
    { strip_frontmatter < "$src_ref"; } | emit_rule "$target" "$desc" "false" "reference/$name.md"
done

# --- 5. Commands -------------------------------------------------------------
CMD_NAMES=()
for cmd_file in "$REPO_ROOT"/commands/*.md; do
    name=$(basename "$cmd_file" .md)
    CMD_NAMES+=("$name")
done
IFS=$'\n' read -r -d '' -a CMD_NAMES_SORTED < <(printf '%s\n' "${CMD_NAMES[@]}" | sort -u && printf '\0') || true
unset IFS

for name in "${CMD_NAMES_SORTED[@]}"; do
    src_cmd="$REPO_ROOT/commands/$name.md"
    # Naming: temper.md -> temper.md; {name}.md -> temper-{name}.md
    if [[ "$name" == "temper" ]]; then
        target="$COMMANDS_DIR/temper.md"
    else
        target="$COMMANDS_DIR/temper-$name.md"
    fi
    desc=$(derive_description "$src_cmd")
    [[ -z "$desc" ]] && desc="Temper command: $name"
    # Commands re-emit a fresh frontmatter (description [+ argument-hint]) then
    # the frozen-note header and the body. The body is run through freeze_filter,
    # which strips post-v5.1 feature blocks (model routing, v2 telemetry, drift,
    # economics) so the FROZEN Cursor export stays on the v5.1 platform track.
    REPO_ROOT_FOR_REL="$REPO_ROOT" python3 - "$src_cmd" "$desc" "$REPO_ROOT" <<'PY' > "$target"
import re, sys
src, desc, repo_root = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(src, encoding='utf-8').read()
arg_hint = None
m = re.match(r'^---\s*\n(.*?)\n---\s*\n?', text, re.DOTALL)
if m:
    fm = m.group(1)
    body = text[m.end():]
    am = re.search(r'^argument-hint:\s*(.+?)\s*$', fm, re.MULTILINE)
    if am:
        arg_hint = am.group(1).strip()
else:
    body = text

def freeze_filter(body):
    """Strip post-v5.1 feature blocks so the Cursor export stays frozen at v5.1.

    The freeze (CHANGELOG v5.2.1) is a platform-strategy policy: Cursor is on the
    v5.1 track and does NOT receive v5.2+ features. We strip the markers those
    features introduced so a derived cursor command never carries them:
      - [MODEL: ...] delta lines (v5.6.0 model routing on Agent launches)
      - [CACHE: ...] delta lines (v5.9.0 cache routing on Agent launches)
      - v5.6/v5.9 section headers (Model/Cache Routing Resolution, Observability
        Tracking, Drift, Economics/Dashboard, Depth tier display) — skipped whole
      - v5.9 Phase 3 marker lines: any line mentioning tokens.cache /
        tokens.adaptive-depth / tokens.loops / Pipeline Depth / Loop Cost /
        cached_input / cacheable prefix / inline-threshold / fix-mode preamble /
        DEPTH CONTRACT / loop cost tier is dropped (Phase 3 is woven through many
        sections, so a line-level scrub is the robust policy)
    Any reference doc that is itself v5.6+ only (pricing.md, tokenomics.md) is
    excluded from the reference export loop entirely. Stripping is line-oriented
    and idempotent.
    """
    # Phase 3 marker terms — any line mentioning one is dropped entirely.
    phase3_markers = (
        'tokens.cache', 'tokens.adaptive-depth', 'tokens.loops',
        'Pipeline Depth', 'Loop Cost', 'cached_input', 'cacheable prefix',
        'cacheable-first', 'inline-threshold', 'fix-mode preamble',
        'DEPTH CONTRACT', 'loop cost tier', 'Cache Routing Resolution',
        'Escalate to full pipeline', 'depth tier', 'adaptive-depth',
        'cache.enabled', 'fix-mode', 'cache.prefix', 'cached prefix',
    )
    out = []
    skip_section = False
    skip_section_hdr = None
    skip_para = False  # True while inside a Phase 3 contract paragraph
    for line in body.splitlines():
        # 0. Paragraph-level freeze: a Phase 3 contract paragraph (DEPTH CONTRACT,
        #    Cache Routing Resolution, depth-tier display, loop cost) is a discrete
        #    multi-line block whose later continuation lines carry NO marker term.
        #    When the paragraph opener is hit, drop the whole block through the next
        #    blank line so continuation lines like "MUST be returned to the
        #    orchestrator ... Escalate to full pipeline" do not leak through 1b.
        if skip_para:
            if line.strip() == '':
                skip_para = False
                # fall through: the blank line ends the block, drop it too
            continue
        if re.match(r'^(#{0,6}\s\**)?(DEPTH CONTRACT|Cache Routing Resolution|Depth tier display|Loop Cost Tier)', line) \
                or line.startswith('DEPTH CONTRACT') \
                or line.startswith('**DEPTH CONTRACT') \
                or line.startswith('Cache Routing Resolution') \
                or line.startswith('**Cache Routing Resolution') \
                or line.startswith('Depth tier display') \
                or line.startswith('**Depth tier display'):
            skip_para = True
            continue
        # 1. Drop [MODEL: ...] and [CACHE: ...] delta lines entirely.
        if re.match(r'^\[MODEL:', line):
            continue
        if re.match(r'^\[CACHE:', line):
            continue
        # 1b. Drop any line mentioning a Phase 3 marker term.
        if any(m in line for m in phase3_markers):
            continue
        # 2. Section-level freeze: when we hit a v5.6/v5.9 section header, skip
        #    until the next same-or-shallower '## ' header.
        hdr = re.match(r'^(##+) (.+)$', line)
        if hdr and any(v in hdr.group(2) for v in ('v5.6.0', 'v5.9.0')) and any(
            kw in hdr.group(2) for kw in (
                'Model Routing Resolution', 'Cache Routing Resolution',
                'Observability Tracking', 'Drift Detection',
                'Economics Panel', 'Observability Dashboard',
                'Depth tier display',
            )
        ):
            skip_section = True
            skip_section_hdr = hdr.group(1)  # the '##' or '###' prefix
            continue
        if skip_section:
            # A new header at the same or shallower depth ends the skipped section.
            nh = re.match(r'^(##+) (.+)$', line)
            if nh and len(nh.group(1)) <= len(skip_section_hdr):
                skip_section = False
                skip_section_hdr = None
                # fall through and emit this header
            else:
                continue
        out.append(line)
    # Trim trailing blank lines left by stripped sections, then restore one.
    result = '\n'.join(out).rstrip('\n')
    if result:
        result += '\n'
    return result

body = freeze_filter(body)
print('---')
print(f'description: "{desc}"')
if arg_hint:
    print(f'argument-hint: {arg_hint}')
print('---')
print()
print('<!--')
print('  AUTO-GENERATED by scripts/generate-cursor.sh from plugin sources.')
print('  Cursor support FROZEN at v5.1 feature set (CHANGELOG v5.2.1).')
print('  This file is regenerated on every release for consistency; do not hand-edit.')
import os
print(f'  Source: {os.path.relpath(src, repo_root)}')
print('-->')
print()
sys.stdout.write(body)
PY
done

# --- 6. VERSION + README -----------------------------------------------------
printf '%s\n' "$VERSION" > "$CURSOR_DIR/VERSION"

cat > "$CURSOR_DIR/README.md" <<EOF
# Temper — Cursor IDE export

**Frozen at v5.1 feature set** (per CHANGELOG v5.2.1 platform strategy).
Regenerated from plugin sources on every release via \`scripts/generate-cursor.sh\`.

Version: $VERSION
Do not hand-edit files in this directory — they are derived.
EOF

# --- Summary -----------------------------------------------------------------
RULE_COUNT=$(find "$RULES_DIR" -name '*.mdc' | wc -l | tr -d ' ')
CMD_COUNT=$(find "$COMMANDS_DIR" -name '*.md' | wc -l | tr -d ' ')
echo "Generated .cursor/ from plugin sources (version $VERSION)"
echo "  Rules:    $RULE_COUNT"
echo "  Commands: $CMD_COUNT"
echo "Cursor support frozen at v5.1 feature set (CHANGELOG v5.2.1)."
